openapi: 3.0.1
info:
  title: Unofficial SureFlap API
  description: "This is a wrapper API for the official SurePetcare API . You can find out more about the installation and usage of this API by visiting the corresponding GitHub repository at [https://gitlab.com/home-automation-fabieu/sureflap-rest-api](https://gitlab.com/home-automation-fabieu/sureflap-rest-api)"
  contact:
    email: dev@sustineo.de
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:3001
tags:
  - name: Dashboard
    description: Access to the overview
  - name: Households
    description: Everything about your households and users
  - name: Pets
    description: Everything about your pets
  - name: Devices
    description: Everything about your devices
paths:
  /dashboard:
    get:
      tags:
        - Dashboard
      summary: Returns an overview of all devices, households,, pets photos, tags and user
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Dashboard"
        "403":
          description: Authorization information is missing or invalid. Check the config.ini!
  /devices:
    get:
      tags:
        - Devices
      summary: Return a list of all registred devices
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  anyOf:
                    - $ref: "#/components/schemas/Hub Short"
                    - $ref: "#/components/schemas/Flap Short"
        "403":
          description: Authorization information is missing or invalid. Check the config.ini
  /devices/{deviceID}:
    get:
      tags:
        - Devices
      summary: Return detailed informations about a specific device
      parameters:
        - in: path
          name: deviceID
          schema:
            type: integer
          required: true
          description: Numeric ID of the device
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: "#/components/schemas/Hub"
                  - $ref: "#/components/schemas/Flap"
        "403":
          description: Authorization information is missing or invalid. Check the config.ini!
components:
  schemas:
    Dashboard:
      type: object
      properties:
        devices:
          type: array
          items:
            anyOf:
              - $ref: "#/components/schemas/Hub Short"
              - $ref: "#/components/schemas/Flap Short"
        households:
          type: array
          items:
            type: object
        pets:
          type: array
          items:
            type: object
        photos:
          type: array
          items:
            type: object
        tags:
          type: array
          items:
            type: object
        user:
          type: object
    Hub:
      type: object
      properties:
        children:
          type: array
          items:
            $ref: "#/components/schemas/Flap Short"
        control:
          type: object
          properties:
            led_mode:
              type: number
            pairing_mode:
              type: number
        created_at:
          type: string
        household_id:
          type: number
        mac_adress:
          type: string
        name:
          type: string
        product_id:
          type: number
        serial_number:
          type: string
        status:
          type: object
          properties:
            led_mode:
              type: string
            online:
              type: boolean
            pairing_mode:
              type: number
            version:
              type: object
              properties:
                device:
                  type: object
                  properties:
                    firmware:
                      type: number
                    hardware:
                      type: number
        updated_at:
          type: string
          format: date-time
        version:
          type: string
    Flap:
      type: object
      properties:
        control:
          type: object
          properties:
            curfew:
              type: object
              properties:
                enabled:
                  type: boolean
                lock_time:
                  type: string
                  format: time
            fast_polling:
              type: boolean
        created_at:
          type: string
          format: date-time
        household_id:
          type: number
        id:
          type: number
        index:
          type: number
        mac_adress:
          type: string
        name:
          type: string
        pairing_at:
          type: string
          format: date-time
        parent:
          $ref: "#/components/schemas/Hub Short"
        parent_device_id:
          type: number
        product_id:
          type: number
        status:
          type: object
          properties:
        updated_at:
          type: string
          format: date-time
        version:
          type: string
    Hub Short:
      type: object
      properties:
        created_at:
          type: string
          format: date-time
        household_id:
          type: number
        id:
          type: number
        name:
          type: string
        product_id:
          type: number
        serial_number:
          type: string
        updated_at:
          type: string
          fornat: date-time
        version:
          type: string
    Flap Short:
      type: object
      properties:
        created_at:
          type: string
          format: date-time
        household_id:
          type: number
        id:
          type: number
        index:
          type: number
        name:
          type: string
        pairing_at:
          type: string
          format: date-time
        parent_device_id:
          type: number
        product_id:
          type: number
        updated_at:
          type: string
          fornat: date-time
        version:
          type: string
